# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 11:16
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sensoriumSite.placeholderModels.aboutUs_placeholders
import sensoriumSite.placeholderModels.equipment_placeholders
import sensoriumSite.placeholderModels.home_placeholders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs_descriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.placeholderModels.aboutUs_placeholders.slot_Description, to='cms.Placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='equipment_descriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.placeholderModels.equipment_placeholders.slot_description, to='cms.Placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='home_descriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.placeholderModels.home_placeholders.slot_description, to='cms.Placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensoriumsite_testplugin', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
