# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='text'),
            preserve_default=False,
        ),
    ]
