# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0002_mainmodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='text',
        ),
    ]
