# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 13:49
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sensoriumSite.placeholderModels.aboutUs_placeholders


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0002_sensorium_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs_BioPlaceholderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_bio', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.placeholderModels.aboutUs_placeholders.slot_Description, to='cms.Placeholder')),
            ],
        ),
    ]
