# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0003_aboutus_bioplaceholdermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorium_bio',
            name='img_name',
            field=models.CharField(max_length=1000),
        ),
    ]
