# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 17:22
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion
import sensoriumSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0004_auto_20190425_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorium_bio',
            name='plc_description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.models.bioName, to='cms.Placeholder'),
        ),
    ]
