# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0004_auto_20190412_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensoriumsite_testplugin', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
