# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 16:00
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion
import sensoriumSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0006_auto_20190412_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymainmodel',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='mymainmodel',
            name='my_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.models.slot_siteDescription, to='cms.Placeholder'),
        ),
    ]
