# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 20:08
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sensoriumSite.placeholderModels.aboutUs_placeholders


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0006_plc_alistairlawson_description_plc_augustoesteves_description_plc_callumegan_description_plc_clairea'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_eventsPlaceholderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_news', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.placeholderModels.aboutUs_placeholders.slot_Description, to='cms.Placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Sensorium_News',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensoriumsite_sensorium_news', serialize=False, to='cms.CMSPlugin')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=500)),
                ('Sub_content', models.CharField(max_length=1000)),
                ('Image_Source', models.CharField(max_length=5000)),
                ('plc_news', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='News/Events', to='cms.Placeholder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
