# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0007_auto_20190413_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymainmodel',
            old_name='my_placeholder',
            new_name='plc_description',
        ),
    ]
