# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 20:10
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0007_news_eventsplaceholdermodel_sensorium_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_eventsplaceholdermodel',
            name='plc_news',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='News/Events', to='cms.Placeholder'),
        ),
    ]
