# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 16:38
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sensoriumSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0008_auto_20190413_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_about_us', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=sensoriumSite.models.slot_aboutUsDescription, to='cms.Placeholder')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymainmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymainmodel',
            name='text',
        ),
    ]
