# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0008_auto_20190428_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorium_news',
            name='Facebook_link',
            field=models.CharField(default='n/a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorium_news',
            name='Linkedin_link',
            field=models.CharField(default='n/a', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorium_news',
            name='Twitter_link',
            field=models.CharField(default='n/a', max_length=500),
            preserve_default=False,
        ),
    ]
