# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 21:12
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0011_auto_20190428_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus_bioplaceholdermodel',
            name='plc_bio',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='Bio Line', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='aboutus_descriptionmodel',
            name='plc_description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='Main Description', to='cms.Placeholder'),
        ),
    ]
