# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriumSite', '0012_auto_20190428_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc_alistairlawson_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_augustoesteves_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_callumegan_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_clairealexander_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_drrichardhetherington_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_drthomasmethven_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_ingihelgason_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_johnmorisson_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_lauramuir_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_olimival_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_profxiaodongliu_description',
            name='plc',
        ),
        migrations.RemoveField(
            model_name='plc_qiliu_description',
            name='plc',
        ),
        migrations.DeleteModel(
            name='plc_AlistairLawson_description',
        ),
        migrations.DeleteModel(
            name='plc_AugustoEsteves_description',
        ),
        migrations.DeleteModel(
            name='plc_CallumEgan_description',
        ),
        migrations.DeleteModel(
            name='plc_ClaireAlexander_description',
        ),
        migrations.DeleteModel(
            name='plc_DrRichardHetherington_description',
        ),
        migrations.DeleteModel(
            name='plc_DrThomasMethven_description',
        ),
        migrations.DeleteModel(
            name='plc_IngiHelgason_description',
        ),
        migrations.DeleteModel(
            name='plc_JohnMorisson_description',
        ),
        migrations.DeleteModel(
            name='plc_LauraMuir_description',
        ),
        migrations.DeleteModel(
            name='plc_OliMival_description',
        ),
        migrations.DeleteModel(
            name='plc_ProfXiaodongLiu_description',
        ),
        migrations.DeleteModel(
            name='plc_QiLiu_description',
        ),
    ]
