# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 23:13
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0015_aboutus_bioplaceholdermodel3_aboutus_bioplaceholdermodel4'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_PlaceholderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_project', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='Project', to='cms.Placeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Sensorium_Project',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensoriumsite_sensorium_project', serialize=False, to='cms.CMSPlugin')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=500)),
                ('Sub_content', models.CharField(max_length=1000)),
                ('Image_Source', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
