# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sensoriumSite', '0016_project_placeholdermodel_sensorium_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_Backs',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sensoriumsite_image_backs', serialize=False, to='cms.CMSPlugin')),
                ('homeBack', models.CharField(max_length=5000)),
                ('contentBack', models.CharField(max_length=5000)),
                ('equipmentBack', models.CharField(max_length=5000)),
                ('newsBack', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='testplugin',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TestPlugin',
        ),
    ]
